name: Source Deploy Manual

on:
  workflow_dispatch:
    inputs:
      deployId:
        description: 'Validated Deploy Request Id'
        required: true

env:
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_COMMIT_BRANCH: ${{ github.ref_name	 }}
  SFDX_AUTH_URL_MAIN: ${{ secrets.SFDX_AUTH_URL_MAIN }}
  SFDX_AUTH_URL_UAT: ${{ secrets.SFDX_AUTH_URL_UAT }}
  SFDX_AUTH_URL_SIT: ${{ secrets.SFDX_AUTH_URL_SIT }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  Tagging:
    needs: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          custom_tag: _deploy_${{ github.sha }}
          tag_prefix: tag-${{ github.ref_name }}

  Deploy:
    runs-on: ubuntu-latest
    container: bitmist/cicd:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deploy script
        run: |
          branch_name=$(echo "$CI_COMMIT_BRANCH" | tr '[:lower:]' '[:upper:]')
          echo "branch_name" $branch_name

          sfdx_auth_url_value=${{ secrets[format('SFDX_AUTH_URL_{0}', env.CI_COMMIT_BRANCH )] }}

          if [ -z "$sfdx_auth_url_value" ]; then
            echo "---- Missing $sfdx_auth_url from CI/CD variables ----"
            exit 1
          fi
          echo sfdx_auth_url $sfdx_auth_url_value
          echo $sfdx_auth_url_value > env.sfdx
          
          validatedDeployRequestId=${{ github.event.inputs.deployId }}
          echo "validatedDeployRequestId" $validatedDeployRequestId
          
          if [ -z "$validatedDeployRequestId" ]; then
            echo "---- Validated Deploy Request Id not found ----"
            exit 1
          else
            sfdx org:login:sfdx-url --sfdx-url-file env.sfdx --set-default
            sfdx force:source:deploy --validateddeployrequestid $validatedDeployRequestId --wait 100 --verbose
          fi
        shell: bash